# docker run --name=rtsp-server --env=RTSP_PROTOCOLS=tcp -p 1935:1935 -p 8554:8554 -p 8888:8888 --restart=always --detach=true aler9/rtsp-simple-server
# docker run --name=ffmpeg --volume=/home/ivan/testsrc.mpg:/testsrc.mpg --link rtsp-server --restart=always --detach=true jrottenberg/
# ffmpeg -re -stream_loop -1 -i /testsrc.mpg -c copy -f rtsp rtsp://rtsp-server:8554/mystream

version: "3.3"
services:
  rtsp-server:
    ports:
      - "1935:1935"
      - "8554:8554"
      - "8888:8888"
    environment:
      - RTSP_PROTOCOLS=tcp
    image: aler9/rtsp-simple-server

  city-traffic:
    image: linuxserver/ffmpeg:version-4.4-cli
    links:
      - "rtsp-server:rtsp-server"
    depends_on:
      - rtsp-server
    command: -re -stream_loop -1 -i https://eu-central-1.linodeobjects.com/savant-data/demo/Free_City_Street_Footage.mp4 -c copy -bsf:v h264_mp4toannexb -f rtsp rtsp://rtsp-server:8554/city-traffic

  local-loop:
    image: linuxserver/ffmpeg:version-4.4-cli
    links:
      - "rtsp-server:rtsp-server"
    depends_on:
      - rtsp-server
    volumes:
      - ./samples/input_files/:/tmp/
    command: -re -stream_loop -1 -i /tmp/testsrc_01.mpg -c copy -f rtsp rtsp://rtsp-server:8554/local-loop

  prepare-input-files:
    image: python:slim-bullseye
    working_dir: /app
    volumes:
       - ./samples/input_files/:/tmp/
       - ./scripts/list_input_files.py:/app/list_input_files.py
    command: python list_input_files.py /tmp/

  concatenated-sample:
    image: linuxserver/ffmpeg:version-4.4-cli
    links:
      - "rtsp-server:rtsp-server"
    depends_on:
      prepare-input-files:
        condition: service_completed_successfully
      rtsp-server:
        condition: service_started
    volumes:
       - ./samples/input_files/:/tmp/
    command: -re -f concat -i /tmp/concat.txt -c copy -f rtsp rtsp://rtsp-server:8554/concatenated-sample
